FROM xcompile-rpi4:sysroot

ARG BINUTILS=binutils-2.40
ARG MUSL=musl-1.2.4
ARG GLIBC=glibc-2.37
ARG GCC=gcc-12.2.0

ARG CMAKE_VERSION=3.26.3

ARG MACHTYPE=x86_64-pc-linux-gnu
ARG CROSS=/cross-$GCC-armv8-a
ARG COMPILE_OPTIONS="--with-arch=armv8-a --with-tune=cortex-a72 --with-fpu=neon-fp-armv8 --with-float=hard --with-sysroot=$SYSROOT"

ARG GLIBC_TARGET=arm-linux-gnueabihf
ARG MUSL_TARGET=arm-linux-musleabihf

