FROM xcompile-rpi4:sysroot

ENV BINUTILS=binutils-2.40
ENV MUSL=musl-1.2.4
ENV GCC=gcc-12.2.0

ENV TARGET=arm-linux-musleabihf
ENV MACHTYPE=x86_64-pc-linux-gnu
ENV CROSS=/cross-$GCC-armv8-a
ENV COMPILE_OPTIONS="--with-arch=armv8-a --with-tune=cortex-a72 --with-fpu=neon-fp-armv8 --with-float=hard --disable-multilib --enable-gold --enable-lto --with-sysroot=$SYSROOT"
